# Workflow - Here we define the workflow name and trigger

name: CI for Terraform

on:
  workflow_dispatch:

permissions:
  contents: write

# Jobs - We can define multiple jobs here

jobs:
  terraform-ci:
    runs-on: ubuntu-latest

    steps:
       # Code Download
      - name: Code clone
        uses: actions/checkout@v7

       # AZ CLi download
      - name: AZ cli install
        uses: pietrobolcato/install-azure-cli-action@main

        # Terraform Setup
      - name: Terraform install
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.7.5"
          
        # Login to Azure using OIDC
        
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
   
        
      # Step 1
      - name: Terraform Init
        run: terraform init

      # Step 2
      - name: Terraform Plan
        run: terraform plan

      # Step 3
      - name: Terraform Apply
        run: terraform apply -auto-approve
      




#Actions

